#!/usr/bin/env python3
"""Generate KV metric C++ definitions and synchronize UCM defaults."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "kv_semantics/metrics/config/kv_metrics.yaml"
HEADER = ROOT / "kv_semantics/metrics/include/kv_metrics/metric_names.h"
DEFAULT_HEADER = (
    ROOT / "kv_semantics/metrics/include/kv_metrics/default_metric_descriptors.h"
)
UCM_YAML = ROOT / "examples/metrics/metrics_configs.yaml"
UCM_PYTHON = ROOT / "ucm/default_metrics_config.py"
SECTIONS = ("counter", "gauge", "histogram")
BEGIN = "BEGIN GENERATED KV METRICS"
END = "END GENERATED KV METRICS"


def load_definitions() -> dict[str, list[dict]]:
    definitions: dict[str, list[dict]] = {section: [] for section in SECTIONS}
    section = ""
    field_pattern = re.compile(
        r"([a-z_]+):\s*(?:\"((?:\\.|[^\"])*)\"|\[([^\]]*)\])"
    )
    for line_number, raw_line in enumerate(
        SOURCE.read_text(encoding="utf-8").splitlines(), start=1
    ):
        stripped = raw_line.strip()
        if stripped in {f"{name}:" for name in SECTIONS}:
            section = stripped[:-1]
            continue
        if not section or not stripped.startswith("- {"):
            continue
        metric: dict = {}
        for match in field_pattern.finditer(stripped):
            key, quoted, sequence = match.groups()
            if sequence is not None:
                metric[key] = [float(value.strip()) for value in sequence.split(",") if value.strip()]
            else:
                metric[key] = json.loads(f'"{quoted}"')
        if not metric:
            raise ValueError(f"cannot parse metric at {SOURCE}:{line_number}")
        definitions[section].append(metric)

    seen_ids: set[str] = set()
    seen_names: set[str] = set()
    for section in SECTIONS:
        for metric in definitions[section]:
            metric_id = metric.get("id", "")
            name = metric.get("name", "")
            if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", metric_id):
                raise ValueError(f"invalid or missing metric id for {name!r}: {metric_id!r}")
            if not re.fullmatch(r"[a-zA-Z_:][a-zA-Z0-9_:]*", name):
                raise ValueError(f"invalid metric name: {name!r}")
            if metric_id in seen_ids:
                raise ValueError(f"duplicate metric id: {metric_id}")
            if name in seen_names:
                raise ValueError(f"duplicate metric name: {name}")
            if not metric.get("documentation"):
                raise ValueError(f"missing documentation for {name}")
            if section == "histogram" and not metric.get("buckets"):
                raise ValueError(f"missing histogram buckets for {name}")
            seen_ids.add(metric_id)
            seen_names.add(name)
    return definitions


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def yaml_number(value: int | float) -> str:
    if isinstance(value, float) and value != 0.0 and abs(value) < 0.0001:
        return f"{value:.15f}".rstrip("0")
    return repr(value)


def yaml_number_list(values: list[int | float]) -> str:
    return "[" + ", ".join(yaml_number(value) for value in values) + "]"


def render_header(definitions: dict[str, list[dict]]) -> str:
    metrics = [
        (metric, section.upper())
        for section in SECTIONS
        for metric in definitions[section]
    ]
    macro_lines = []
    for index, (metric, metric_type) in enumerate(metrics):
        suffix = " \\" if index + 1 < len(metrics) else ""
        macro_lines.append(
            f"    X({metric['id']}, {cpp_string(metric['name'])}, {metric_type}, "
            f"{cpp_string(metric['documentation'])}){suffix}"
        )
    macro = "\n".join(macro_lines)
    return f'''#pragma once

// Generated by kv_semantics/metrics/tools/generate_kv_metrics.py from
// kv_semantics/metrics/config/kv_metrics.yaml. Do not edit by hand.

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace kv::metrics {{

#define KV_BUILTIN_METRIC_LIST(X) \\
{macro}

enum class KvMetricId : std::uint8_t {{
#define KV_DECLARE_METRIC_ID(id, name, type, documentation) id,
    KV_BUILTIN_METRIC_LIST(KV_DECLARE_METRIC_ID)
#undef KV_DECLARE_METRIC_ID
        COUNT,
}};

inline constexpr std::size_t kBuiltinMetricCount =
    static_cast<std::size_t>(KvMetricId::COUNT);

constexpr std::size_t ToIndex(KvMetricId id) noexcept
{{
    return static_cast<std::size_t>(id);
}}

constexpr std::string_view MetricName(KvMetricId id) noexcept
{{
    switch (id) {{
#define KV_METRIC_NAME_CASE(metricId, name, type, documentation) \\
    case KvMetricId::metricId: return name;
        KV_BUILTIN_METRIC_LIST(KV_METRIC_NAME_CASE)
#undef KV_METRIC_NAME_CASE
        case KvMetricId::COUNT: return {{}};
    }}
    return {{}};
}}

namespace Names {{
#define KV_DECLARE_METRIC_NAME(id, name, type, documentation) \\
    inline constexpr std::string_view id = name;
KV_BUILTIN_METRIC_LIST(KV_DECLARE_METRIC_NAME)
#undef KV_DECLARE_METRIC_NAME
}}  // namespace Names

}}  // namespace kv::metrics
'''


def cpp_number(value: int | float) -> str:
    return repr(value)


def render_default_header(definitions: dict[str, list[dict]]) -> str:
    entries: list[str] = []
    for section in SECTIONS:
        for metric in definitions[section]:
            buckets = metric.get("buckets", [])
            bucket_values = "{" + ", ".join(cpp_number(value) for value in buckets) + "}"
            entries.append(
                "        {"
                f"{cpp_string(metric['name'])}, MetricType::{section.upper()}, "
                f"{cpp_string(metric['documentation'])}, {bucket_values}"
                "},"
            )
    body = "\n".join(entries)
    return f'''#pragma once

// Generated by kv_semantics/metrics/tools/generate_kv_metrics.py from
// kv_semantics/metrics/config/kv_metrics.yaml. Do not edit by hand.

#include <vector>
#include "kv_metrics/metric_descriptor.h"

namespace kv::metrics {{

inline std::vector<MetricDescriptor> DefaultKvMetricDescriptors()
{{
    return {{
{body}
    }};
}}

}}  // namespace kv::metrics
'''


def replace_section_block(text: str, section: str, body: list[str]) -> str:
    section_match = re.search(rf"(?m)^{re.escape(section)}:\s*$", text)
    if not section_match:
        raise ValueError(f"missing section {section!r}")
    begin = text.find(BEGIN, section_match.end())
    end = text.find(END, begin)
    if begin < 0 or end < 0:
        raise ValueError(f"missing generated markers in section {section!r}")
    begin_line_end = text.find("\n", begin) + 1
    end_line_start = text.rfind("\n", 0, end) + 1
    return text[:begin_line_end] + "\n".join(body) + "\n" + text[end_line_start:]


def render_ucm_yaml(current: str, definitions: dict[str, list[dict]]) -> str:
    result = current
    for section in SECTIONS:
        lines: list[str] = []
        for metric in definitions[section]:
            lines.append(f"  - name: {cpp_string(metric['name'])}")
            lines.append(f"    documentation: {cpp_string(metric['documentation'])}")
            if section == "histogram":
                lines.append(f"    buckets: {yaml_number_list(metric['buckets'])}")
            if "multiprocess_mode" in metric:
                lines.append(
                    f"    multiprocess_mode: {cpp_string(metric['multiprocess_mode'])}"
                )
        result = replace_section_block(result, section, lines)
    return result


def render_python_entry(section: str, metric: dict) -> list[str]:
    name = repr(metric["name"])
    documentation = repr(metric["documentation"])
    if section == "counter":
        return [f"    ({name}, {documentation}),"]
    if section == "gauge":
        extra = {
            key: value
            for key, value in metric.items()
            if key not in {"id", "name", "documentation", "buckets"}
        }
        return [f"    ({name}, {documentation}, {extra!r}),"]
    return [f"    ({name}, {documentation}, {metric['buckets']!r}),"]


def render_ucm_python(current: str, definitions: dict[str, list[dict]]) -> str:
    result = current
    python_sections = {
        "counter": "_COUNTER_METRICS = [",
        "gauge": "_GAUGE_METRICS = [",
        "histogram": "_HISTOGRAM_METRICS = [",
    }
    for section, heading in python_sections.items():
        section_start = result.find(heading)
        if section_start < 0:
            raise ValueError(f"missing Python section {heading!r}")
        begin = result.find(BEGIN, section_start)
        end = result.find(END, begin)
        if begin < 0 or end < 0:
            raise ValueError(f"missing Python generated markers for {section}")
        begin_line_end = result.find("\n", begin) + 1
        end_line_start = result.rfind("\n", 0, end) + 1
        body = [
            line
            for metric in definitions[section]
            for line in render_python_entry(section, metric)
        ]
        result = result[:begin_line_end] + "\n".join(body) + "\n" + result[end_line_start:]
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail when generated files are out of date"
    )
    parser.add_argument(
        "--header-only",
        action="store_true",
        help="only generate the standalone C++ header (used by standalone builds)",
    )
    args = parser.parse_args()

    definitions = load_definitions()
    outputs = {
        HEADER: render_header(definitions),
        DEFAULT_HEADER: render_default_header(definitions),
    }
    if not args.header_only:
        outputs[UCM_YAML] = render_ucm_yaml(
            UCM_YAML.read_text(encoding="utf-8"), definitions
        )
        outputs[UCM_PYTHON] = render_ucm_python(
            UCM_PYTHON.read_text(encoding="utf-8"), definitions
        )
    stale = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if args.check:
        if stale:
            for path in stale:
                print(f"out of date: {path.relative_to(ROOT)}")
            return 1
        return 0
    for path, content in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"generated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
