#pragma once

// Generated by kv_semantics/metrics/tools/generate_kv_metrics.py from
// kv_semantics/metrics/config/kv_metrics.yaml. Do not edit by hand.

#include <vector>
#include "kv_metrics/metric_descriptor.h"

namespace kv::metrics {

inline std::vector<MetricDescriptor> DefaultKvMetricDescriptors()
{
    return {
        {"kv_client_query_requests_total", MetricType::COUNTER, "Total KV client query submissions", {}},
        {"kv_client_query_entries_total", MetricType::COUNTER, "Total keys submitted to KV client query", {}},
        {"kv_client_query_errors_total", MetricType::COUNTER, "Total failed KV client query submissions", {}},
        {"kv_client_load_requests_total", MetricType::COUNTER, "Total KV client load submissions", {}},
        {"kv_client_load_entries_total", MetricType::COUNTER, "Total entries submitted to KV client load", {}},
        {"kv_client_load_errors_total", MetricType::COUNTER, "Total failed KV client load submissions", {}},
        {"kv_client_store_requests_total", MetricType::COUNTER, "Total KV client store submissions", {}},
        {"kv_client_store_entries_total", MetricType::COUNTER, "Total entries submitted to KV client store", {}},
        {"kv_client_store_errors_total", MetricType::COUNTER, "Total failed KV client store submissions", {}},
        {"kv_client_batch_load_requests_total", MetricType::COUNTER, "Total KV client batch-load submissions", {}},
        {"kv_client_batch_load_entries_total", MetricType::COUNTER, "Total entries submitted to KV client batch-load", {}},
        {"kv_client_batch_load_errors_total", MetricType::COUNTER, "Total failed KV client batch-load submissions", {}},
        {"kv_client_batch_store_requests_total", MetricType::COUNTER, "Total KV client batch-store submissions", {}},
        {"kv_client_batch_store_entries_total", MetricType::COUNTER, "Total entries submitted to KV client batch-store", {}},
        {"kv_client_batch_store_errors_total", MetricType::COUNTER, "Total failed KV client batch-store submissions", {}},
        {"kv_client_delete_requests_total", MetricType::COUNTER, "Total KV client delete submissions", {}},
        {"kv_client_delete_entries_total", MetricType::COUNTER, "Total keys submitted to KV client delete", {}},
        {"kv_client_delete_errors_total", MetricType::COUNTER, "Total failed KV client delete submissions", {}},
        {"kv_client_wait_requests_total", MetricType::COUNTER, "Total KV client wait calls", {}},
        {"kv_client_wait_errors_total", MetricType::COUNTER, "Total failed KV client wait calls", {}},
        {"kv_client_task_queue_wait_notified_total", MetricType::COUNTER, "KV client queue waits completed by notification", {}},
        {"kv_client_task_queue_wait_timeout_total", MetricType::COUNTER, "KV client queue waits completed by timeout", {}},
        {"kv_client_task_queue_notify_total", MetricType::COUNTER, "KV client queue notifications", {}},
        {"kv_transport_task_queue_wait_notified_total", MetricType::COUNTER, "KV transport queue waits completed by notification", {}},
        {"kv_transport_task_queue_wait_timeout_total", MetricType::COUNTER, "KV transport queue waits completed by timeout", {}},
        {"kv_transport_task_queue_notify_total", MetricType::COUNTER, "KV transport queue notifications", {}},
        {"kv_metrics_exporter_http_requests_total", MetricType::COUNTER, "HTTP requests served by the KV metrics endpoint", {}},
        {"kv_metrics_exporter_up", MetricType::GAUGE, "Whether the KV standalone metrics exporter is running", {}},
        {"kv_client_query_submit_duration_seconds", MetricType::HISTOGRAM, "KV client query submission duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_load_submit_duration_seconds", MetricType::HISTOGRAM, "KV client load submission duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_store_submit_duration_seconds", MetricType::HISTOGRAM, "KV client store submission duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_batch_load_submit_duration_seconds", MetricType::HISTOGRAM, "KV client batch-load submission duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_batch_store_submit_duration_seconds", MetricType::HISTOGRAM, "KV client batch-store submission duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_delete_submit_duration_seconds", MetricType::HISTOGRAM, "KV client delete submission duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_wait_duration_seconds", MetricType::HISTOGRAM, "KV client wait duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_enqueue_duration_seconds", MetricType::HISTOGRAM, "KV client API-to-enqueue duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_queue_duration_seconds", MetricType::HISTOGRAM, "KV client task queue duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_process_duration_seconds", MetricType::HISTOGRAM, "KV client task processing duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_pre_send_duration_seconds", MetricType::HISTOGRAM, "KV client duration until all transport tasks reach Send", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_send_duration_seconds", MetricType::HISTOGRAM, "KV client duration until all Send calls return", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_duration_seconds", MetricType::HISTOGRAM, "KV client task end-to-end duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_pre_send_duration_seconds", MetricType::HISTOGRAM, "KV transport duration before Send", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_queue_duration_seconds", MetricType::HISTOGRAM, "KV transport task queue duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_process_duration_seconds", MetricType::HISTOGRAM, "KV transport task processing duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_send_duration_seconds", MetricType::HISTOGRAM, "KV transport duration until Send returns", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_completion_duration_seconds", MetricType::HISTOGRAM, "KV transport completion callback duration after Send", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_fake_backend_task_queue_duration_seconds", MetricType::HISTOGRAM, "KV fake backend task queue duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_fake_backend_task_process_duration_seconds", MetricType::HISTOGRAM, "KV fake backend processing duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
    };
}

}  // namespace kv::metrics
