#pragma once

// Generated by generate_kv_metrics.py from kv_metrics.yaml.

#include <vector>
#include "kv_metrics/standalone_metrics_backend.h"

namespace kv::metrics {

inline std::vector<MetricDescriptor> DefaultKvMetricDescriptors()
{
    return {
        {"kv_client_query_requests_total", MetricType::COUNTER, "Total KV client query submissions", {}},
        {"kv_client_query_entries_total", MetricType::COUNTER, "Total keys submitted to KV client query", {}},
        {"kv_client_query_errors_total", MetricType::COUNTER, "Total failed KV client query submissions", {}},
        {"kv_client_load_requests_total", MetricType::COUNTER, "Total KV client load submissions", {}},
        {"kv_client_load_entries_total", MetricType::COUNTER, "Total entries submitted to KV client load", {}},
        {"kv_client_load_errors_total", MetricType::COUNTER, "Total failed KV client load submissions", {}},
        {"kv_client_store_requests_total", MetricType::COUNTER, "Total KV client store submissions", {}},
        {"kv_client_store_entries_total", MetricType::COUNTER, "Total entries submitted to KV client store", {}},
        {"kv_client_store_errors_total", MetricType::COUNTER, "Total failed KV client store submissions", {}},
        {"kv_client_batch_load_requests_total", MetricType::COUNTER, "Total KV client batch-load submissions", {}},
        {"kv_client_batch_load_entries_total", MetricType::COUNTER, "Total entries submitted to KV client batch-load", {}},
        {"kv_client_batch_load_errors_total", MetricType::COUNTER, "Total failed KV client batch-load submissions", {}},
        {"kv_client_batch_store_requests_total", MetricType::COUNTER, "Total KV client batch-store submissions", {}},
        {"kv_client_batch_store_entries_total", MetricType::COUNTER, "Total entries submitted to KV client batch-store", {}},
        {"kv_client_batch_store_errors_total", MetricType::COUNTER, "Total failed KV client batch-store submissions", {}},
        {"kv_client_delete_requests_total", MetricType::COUNTER, "Total KV client delete submissions", {}},
        {"kv_client_delete_entries_total", MetricType::COUNTER, "Total keys submitted to KV client delete", {}},
        {"kv_client_delete_errors_total", MetricType::COUNTER, "Total failed KV client delete submissions", {}},
        {"kv_client_wait_requests_total", MetricType::COUNTER, "Total KV client wait calls", {}},
        {"kv_client_wait_errors_total", MetricType::COUNTER, "Total failed KV client wait calls", {}},
        {"kv_transport_task_completion_timeouts_total", MetricType::COUNTER, "Total KV transport task completion timeouts", {}},
        {"kv_transport_task_io_timeouts_total", MetricType::COUNTER, "Total KV transport sub-batch IO timeouts", {}},
        {"kv_transport_task_connection_errors_total", MetricType::COUNTER, "Total KV transport connection errors", {}},
        {"kv_client_task_enqueue_duration_seconds", MetricType::HISTOGRAM, "KV client API-to-enqueue duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_queue_duration_seconds", MetricType::HISTOGRAM, "KV client task queue duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_process_duration_seconds", MetricType::HISTOGRAM, "KV client task processing duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_send_duration_seconds", MetricType::HISTOGRAM, "KV client duration until all Send calls return", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_task_e2e_duration_seconds", MetricType::HISTOGRAM, "KV client task end-to-end duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_pre_send_duration_seconds", MetricType::HISTOGRAM, "KV transport duration before Send", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_queue_duration_seconds", MetricType::HISTOGRAM, "KV transport task queue duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_process_duration_seconds", MetricType::HISTOGRAM, "KV transport task processing duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_send_duration_seconds", MetricType::HISTOGRAM, "KV transport duration until Send returns", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_send_call_duration_seconds", MetricType::HISTOGRAM, "KV transport provider Send call duration", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_completion_duration_seconds", MetricType::HISTOGRAM, "KV transport completion duration after Send", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_node_task_send_duration_seconds", MetricType::HISTOGRAM, "KV transport send duration by node", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_node_task_completion_duration_seconds", MetricType::HISTOGRAM, "KV transport completion duration by node", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_transport_task_e2e_duration_seconds", MetricType::HISTOGRAM, "KV transport task end-to-end duration from submit to completion", {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
    };
}

}  // namespace kv::metrics
